### ISSUE TITLE
Task display innacurate

### ISSUE THREAD

**Issue by jetpax** [esp32m/core#13]
After a few days of uptime, I'm seeing some curious stats in the Task log...

<img width="589" alt="image" src="https://github.com/esp32m/core/assets/6566148/474f281d-e788-42a2-9e24-5924ea214e2e">

**Comment by dyarkovoy** [comment]
Yes I can understand where that comes from. FreeRTOS has 2 separate functions, one returns total CPU time, and the other returns CPU time per task. The problem is, the first function is limited to 32 bit integer, so it overflows after some time (a couple of days, I believe). I don't think it's critical though, as this Tasks module should be used for debugging purposes and should not be included into production builds anyway

**Comment by jetpax** [comment]
Thanks for the explanation
