### ISSUE TITLE
MQTT Client name

### ISSUE THREAD

**Issue by jetpax** [esp32m/core#21]
If I issue 

`{"type":"request","target":"mqtt","name":"config-set","data":{"client":"foobar"}}`

The client name is updated as expected in the UI
<img width="569" alt="image" src="https://github.com/esp32m/core/assets/6566148/16f6d5db-3261-49ec-a83d-a9723fa457c8">

and an MQTT reconnect is triggered

However, the MQTT broker still shows the topic with  App::instance().hostname())

**Comment by dyarkovoy** [comment]
Hi, @jetpax, this is by design. The client name is not related to the topic. Client name is used by MQTT broker to identify the client for stateful interaction (for example, to allocate storage space for persistent messages). Topic is used in publish/subscribe interaction to identify related messages. When we change client name, topic will not be affected.

**Comment by jetpax** [comment]
Thank you for the clarification.

I wanted to connect several devices to the broker without recompiling, now I understand that I can just change the hostname and reboot.

<img width="581" alt="image" src="https://github.com/esp32m/core/assets/6566148/bb031841-fa84-49c2-9396-6b844222c372">

**Comment by dyarkovoy** [comment]
There's a feature to automatically set the hostname by appending 4 chars of MAC address to the app name, `App::Init::inferHostname()`

**Comment by jetpax** [comment]
Thats perfect, thanks!

Would be nice if there was '_'  between the application name and MAC chars though

eg foobar_e505 instead of foobare505
