### ISSUE TITLE
Obtaining MQTT credentials in an app

### ISSUE THREAD

**Issue by jetpax** [esp32m/core#22]
In my app, I need to publish to a topic prefix that includes the MQTT username and client_id of the connected MQTT session.

I can get this information using the MQTT API with esp32m/request/Appname/mqtt/config-get, but  its not clear to me how to get this from within an app?

Adding a public getter in esp32m/net/mqtt.hpp like
```
      const esp_mqtt_client_config_t getCfg() {
        return _cfg;
      }
```

works if my app then calls 

```
      _topic_prefix.append( net::useMqtt()->getCfg().credentials.username);
      _topic_prefix.append("/");
      _topic_prefix.append( net::useMqtt()->getCfg().credentials.client_id);
      _topic_prefix.append("/");
```
but changes are only valid after a reboot (whereas the API refreshes the info immediately on save and does not require a reboot)

Any suggestions?

**Comment by dyarkovoy** [comment]
In your example, the new username/client ID will be returned shortly after the change (not instantly, because the _cfg is modified in a separate task), but you should definitely see the change without rebooting. After all, the same _cfg is used to set new username/client ID in MQTT client, so if the changes are observed in MQTT connection, it is not possible that they are not observed in _cfg struct.
I would return a reference to the _cfg in the getter to prevent unnecessary copy of the structure:
```
      const esp_mqtt_client_config_t& getCfg() {
        return _cfg;
      }
```

**Comment by jetpax** [comment]
Thanks that works perfectly now (as you suggested I was getting the config too early).

Will you add this or shall I submit a PR?

**Comment by dyarkovoy** [comment]
Added just now

**Comment by jetpax** [comment]
Many thanks!
